## Algerian Forest Fires Dataset 

### Data Set Information:

The dataset includes 244 instances that regroup a data of two regions of Algeria,namely the Bejaia region located in the northeast of Algeria and the Sidi Bel-abbes region located in the northwest of Algeria.

- 122 instances for each region
- The period from June 2012 to September 2012.
- The dataset includes 12 attribues

### Attribute Information:

1. Date : (DD/MM/YYYY) Day, month ('june' to 'september'), year (2012)
Weather data observations
2. Temp : temperature noon (temperature max) in Celsius degrees: 22 to 42
3. RH : Relative Humidity in %: 21 to 90
4. Ws :Wind speed in km/h: 6 to 29
5. Rain: total day in mm: 0 to 16.8
FWI Components
6. Fine Fuel Moisture Code (FFMC) index from the FWI system: 28.6 to 92.5
7. Duff Moisture Code (DMC) index from the FWI system: 1.1 to 65.9
8. Drought Code (DC) index from the FWI system: 7 to 220.4
9. Initial Spread Index (ISI) index from the FWI system: 0 to 18.5
10. Buildup Index (BUI) index from the FWI system: 1.1 to 68
11. Fire Weather Index (FWI) Index: 0 to 31.1
12. Classes: two classes, namely Fire and not Fire

### Problem Statement for this notebook:

Clean-up the data such that it can be used for ML models.


In [1]:
import numpy as np
import pandas as pd

### Priliminary exploration

In [2]:
df = pd.read_csv('Algerian_forest_fires_dataset.csv', header=1)

In [3]:
df

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
0    01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3   3.4   
1    02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1   3.9   
2    03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3   2.7   
3    04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0   1.7   
4    05    06  2012          27  77  16     0  64.8    3  14.2  1.2   3.9   
..   ..   ...   ...         ...  ..  ..   ...   ...  ...   ...  ...   ...   
241  26    09  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
242  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
243  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
244  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
245  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI     Classes    
0    0.5   not fire     
1    0.4   not fire     
2    0.1   not fire     
3      0   not fire     
4    0.5   not fire     
..   ...           ...  
241  6.5       fire     
242    0   not fire     
243  0.2   not fire     
244  0.7   not fire     
245  0.5  not fire      

[246 rows x 14 columns]

In [4]:
df.shape

(246, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          246 non-null    object
 1   month        245 non-null    object
 2   year         245 non-null    object
 3   Temperature  245 non-null    object
 4    RH          245 non-null    object
 5    Ws          245 non-null    object
 6   Rain         245 non-null    object
 7   FFMC         245 non-null    object
 8   DMC          245 non-null    object
 9   DC           245 non-null    object
 10  ISI          245 non-null    object
 11  BUI          245 non-null    object
 12  FWI          245 non-null    object
 13  Classes      245 non-null    object
dtypes: object(14)
memory usage: 27.0+ KB


### Observations:
- Dataset is broken into 2 parts, will need to engineer the features for each region, and merge the dataset.
- Some column names have spaces around them.
- "Classes" is non-numerical and categorical.
- All the columns have been read as "object". 

### Task 1 - merge the dataset:
1. Dataset is divided into 2 parts, by the 2 regions mentioned. Since there is no order/preference between the region, it would be inaccurate to mark one as 0 and another as 1.
2. Hence, create 2 new features, one for each region. Set them to 0 or 1 for each row, according to it's region.
3. Drop rows that are region name or header. Also drop null rows, if any.

In [6]:
df[df.isnull().any(axis=1)]

day month year Temperature   RH   Ws Rain   \
122  Sidi-Bel Abbes Region Dataset   NaN  NaN         NaN  NaN  NaN   NaN   

    FFMC  DMC   DC  ISI  BUI  FWI Classes    
122  NaN  NaN  NaN  NaN  NaN  NaN       NaN

Since only 1 row has null values, and it is the region indicator. Hence, it is safe to drop it.

Also, index 123 is the header row again for the Sidi-Bel region. That also needs to be dropped.

In [7]:
df = df.dropna().reset_index(drop=True)
#index 123 moved to 122
df = df.drop(index=122).reset_index(drop=True)

In [8]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
dtype: int64

In [9]:
df.iloc[120:130]

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
120  29    09  2012          26  80  16   1.8  47.4  2.9   7.7  0.3     3   
121  30    09  2012          25  78  14   1.4    45  1.9   7.5  0.2   2.4   
122  01    06  2012          32  71  12   0.7  57.1  2.5   8.2  0.6   2.8   
123  02    06  2012          30  73  13     4  55.7  2.7   7.8  0.6   2.9   
124  03    06  2012          29  80  14     2  48.7  2.2   7.6  0.3   2.6   
125  04    06  2012          30  64  14     0  79.4  5.2  15.4  2.2   5.6   
126  05    06  2012          32  60  14   0.2  77.1    6  17.6  1.8   6.5   
127  06    06  2012          35  54  11   0.1  83.7  8.4  26.3  3.1   9.3   
128  07    06  2012          35  44  17   0.2  85.6  9.9  28.9  5.4  10.7   
129  08    06  2012          28  51  17   1.3  71.4  7.7   7.4  1.5   7.3   

     FWI    Classes    
120  0.1  not fire     
121  0.1  not fire     
122  0.2  not fire     
123  0.2  not fire     
124  0.1  not fire     
125    1  not fire     
126  0.9  not fire     
127  3.1      fire     
128    6      fire     
129  0.8  not fire

Data points till index 121 belong to the Bejaia region, and the ones from 122 belong to the Sidi-Bel region.
Hence, create a column marking them as 0 and 1 according to the region of each data point

In [10]:
df['Region_Bejaia'] = 0
df.loc[:121, "Region_Bejaia"] = 1

Verify
- Region_Bejaia = 1 for index :121
- Region_Bejaia = 0 for index 122:

In [11]:
df.iloc[120:125]

day month  year Temperature  RH  Ws Rain   FFMC  DMC   DC  ISI  BUI  FWI  \
120  29    09  2012          26  80  16   1.8  47.4  2.9  7.7  0.3    3  0.1   
121  30    09  2012          25  78  14   1.4    45  1.9  7.5  0.2  2.4  0.1   
122  01    06  2012          32  71  12   0.7  57.1  2.5  8.2  0.6  2.8  0.2   
123  02    06  2012          30  73  13     4  55.7  2.7  7.8  0.6  2.9  0.2   
124  03    06  2012          29  80  14     2  48.7  2.2  7.6  0.3  2.6  0.1   

       Classes    Region_Bejaia  
120  not fire                 1  
121  not fire                 1  
122  not fire                 0  
123  not fire                 0  
124  not fire                 0

In [12]:
df.head()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

     Classes    Region_Bejaia  
0  not fire                 1  
1  not fire                 1  
2  not fire                 1  
3  not fire                 1  
4  not fire                 1

In [13]:
df.tail()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI   BUI  \
239  26    09  2012          30  65  14     0  85.4   16  44.5  4.5  16.9   
240  27    09  2012          28  87  15   4.4  41.1  6.5     8  0.1   6.2   
241  28    09  2012          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4   
242  29    09  2012          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1   
243  30    09  2012          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8   

     FWI     Classes    Region_Bejaia  
239  6.5       fire                 0  
240    0   not fire                 0  
241  0.2   not fire                 0  
242  0.7   not fire                 0  
243  0.5  not fire                  0

### Task 2 : Removing spaces from column names

In [14]:
df.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  ', 'Region_Bejaia'],
      dtype='object')

In [15]:
df.columns = df.columns.str.strip()

In [16]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region_Bejaia'],
      dtype='object')

### Task 3 : Convert "Classes" into numerical data
Since there are only 2 categories, and there is a correlation/order among them, mark "no" as 0, and "yes" as "1"

In [17]:
df["Classes"].value_counts()

Classes
fire             132
not fire         101
fire               4
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

The values inside "Classes" seem to have extra spaces around them.
Remove them.

In [18]:
df["Classes"] = df["Classes"].str.strip()

In [19]:
df["Classes"].value_counts()

Classes
fire        138
not fire    106
Name: count, dtype: int64

With only 2 categories, replace the values
Rename "Classes" to "Fire"

In [20]:
df["Fire"] = np.where(df["Classes"] == "not fire", 0, 1)
df = df.drop("Classes", axis=1)

### Task 4 - convert the column data types appropriately

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   day            244 non-null    object
 1   month          244 non-null    object
 2   year           244 non-null    object
 3   Temperature    244 non-null    object
 4   RH             244 non-null    object
 5   Ws             244 non-null    object
 6   Rain           244 non-null    object
 7   FFMC           244 non-null    object
 8   DMC            244 non-null    object
 9   DC             244 non-null    object
 10  ISI            244 non-null    object
 11  BUI            244 non-null    object
 12  FWI            244 non-null    object
 13  Region_Bejaia  244 non-null    int64 
 14  Fire           244 non-null    int32 
dtypes: int32(1), int64(1), object(13)
memory usage: 27.8+ KB


In [22]:
df.head()

day month  year Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  FWI  \
0  01    06  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1  02    06  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2  03    06  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3  04    06  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4  05    06  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

   Region_Bejaia  Fire  
0              1     0  
1              1     0  
2              1     0  
3              1     0  
4              1     0

Int Data Types:
- day
- month
- year
- Temperature
- RH
- Ws

Rest are float data types

In [23]:
df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws']] = df[['day', 'month', 'year', 'Temperature', 'RH', 'Ws']] .astype(int)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   day            244 non-null    int32 
 1   month          244 non-null    int32 
 2   year           244 non-null    int32 
 3   Temperature    244 non-null    int32 
 4   RH             244 non-null    int32 
 5   Ws             244 non-null    int32 
 6   Rain           244 non-null    object
 7   FFMC           244 non-null    object
 8   DMC            244 non-null    object
 9   DC             244 non-null    object
 10  ISI            244 non-null    object
 11  BUI            244 non-null    object
 12  FWI            244 non-null    object
 13  Region_Bejaia  244 non-null    int64 
 14  Fire           244 non-null    int32 
dtypes: int32(7), int64(1), object(7)
memory usage: 22.1+ KB


In [25]:
objects = [features for features in df.columns if df[features].dtypes == 'O']
objects

['Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI']

In [26]:
df[objects] = df[objects].astype(float)

## Verify and save the dataset

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   day            244 non-null    int32  
 1   month          244 non-null    int32  
 2   year           244 non-null    int32  
 3   Temperature    244 non-null    int32  
 4   RH             244 non-null    int32  
 5   Ws             244 non-null    int32  
 6   Rain           244 non-null    float64
 7   FFMC           244 non-null    float64
 8   DMC            244 non-null    float64
 9   DC             244 non-null    float64
 10  ISI            244 non-null    float64
 11  BUI            244 non-null    float64
 12  FWI            244 non-null    float64
 13  Region_Bejaia  244 non-null    int64  
 14  Fire           244 non-null    int32  
dtypes: float64(7), int32(7), int64(1)
memory usage: 22.1 KB


In [28]:
df.shape

(244, 15)

In [29]:
df.head()

day  month  year  Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  \
0    1      6  2012           29  57  18   0.0  65.7  3.4   7.6  1.3  3.4   
1    2      6  2012           29  61  13   1.3  64.4  4.1   7.6  1.0  3.9   
2    3      6  2012           26  82  22  13.1  47.1  2.5   7.1  0.3  2.7   
3    4      6  2012           25  89  13   2.5  28.6  1.3   6.9  0.0  1.7   
4    5      6  2012           27  77  16   0.0  64.8  3.0  14.2  1.2  3.9   

   FWI  Region_Bejaia  Fire  
0  0.5              1     0  
1  0.4              1     0  
2  0.1              1     0  
3  0.0              1     0  
4  0.5              1     0

In [30]:
df.tail()

day  month  year  Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  \
239   26      9  2012           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9   
240   27      9  2012           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2   
241   28      9  2012           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4   
242   29      9  2012           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1   
243   30      9  2012           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8   

     FWI  Region_Bejaia  Fire  
239  6.5              0     1  
240  0.0              0     0  
241  0.2              0     0  
242  0.7              0     0  
243  0.5              0     0

In [31]:
df.loc[120:125]

day  month  year  Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  \
120   29      9  2012           26  80  16   1.8  47.4  2.9   7.7  0.3  3.0   
121   30      9  2012           25  78  14   1.4  45.0  1.9   7.5  0.2  2.4   
122    1      6  2012           32  71  12   0.7  57.1  2.5   8.2  0.6  2.8   
123    2      6  2012           30  73  13   4.0  55.7  2.7   7.8  0.6  2.9   
124    3      6  2012           29  80  14   2.0  48.7  2.2   7.6  0.3  2.6   
125    4      6  2012           30  64  14   0.0  79.4  5.2  15.4  2.2  5.6   

     FWI  Region_Bejaia  Fire  
120  0.1              1     0  
121  0.1              1     0  
122  0.2              0     0  
123  0.2              0     0  
124  0.1              0     0  
125  1.0              0     0

In [32]:
df.to_csv('Algerian_forest_fires_dataset_cleaned.csv', index=False)